In [55]:
# %pylab inline
import math
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
%matplotlib inline

In [56]:
jan = pd.read_csv('chicago_taxi_trips_2016_01.csv')
jan.head()
# jan.info()jan.describe()

,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_latitude,pickup_longitude,dropoff_latitude,dropoff_longitude
0,85.0,2016-1-13 06:15:00,2016-1-13 06:15:00,180.0,0.40,NaN,NaN,24.0,24.0,4.50,0.00,0.0,0.0,4.50,Cash,107.0,199.0,510.0,199.0,510.0
1,2776.0,2016-1-22 09:30:00,2016-1-22 09:45:00,240.0,0.70,NaN,NaN,NaN,NaN,4.45,4.45,0.0,0.0,8.90,Credit Card,NaN,NaN,NaN,NaN,NaN
2,3168.0,2016-1-31 21:30:00,2016-1-31 21:30:00,0.0,0.00,NaN,NaN,NaN,NaN,42.75,5.00,0.0,0.0,47.75,Credit Card,119.0,NaN,NaN,NaN,NaN
3,4237.0,2016-1-23 17:30:00,2016-1-23 17:30:00,480.0,1.10,NaN,NaN,6.0,6.0,7.00,0.00,0.0,0.0,7.00,Cash,NaN,686.0,500.0,686.0,500.0
4,5710.0,2016-1-14 05:45:00,2016-1-14 06:00:00,480.0,2.71,NaN,NaN,32.0,NaN,10.25,0.00,0.0,0.0,10.25,Cash,NaN,385.0,478.0,NaN,NaN

In [57]:
jan.describe()

,taxi_id,trip_seconds,trip_miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,company,pickup_latitude,pickup_longitude,dropoff_latitude,dropoff_longitude
count,1.705782e+06,1.705491e+06,1.705791e+06,0.0,967479.000000,1.420016e+06,1.392150e+06,1.705772e+06,1.705772e+06,1.705772e+06,1.705772e+06,1.705772e+06,1.073079e+06,1.420048e+06,1.420048e+06,1.394123e+06,1.394123e+06
mean,4.389323e+03,6.534422e+02,2.872702e+00,NaN,516.822016,2.322074e+01,2.099069e+01,1.315396e+01,1.515107e+00,4.308202e-03,9.484850e-01,1.562189e+01,9.260232e+01,3.921436e+02,4.377736e+02,4.013053e+02,4.388507e+02
std,2.515819e+03,9.327260e+02,1.810793e+01,NaN,357.586612,1.981936e+01,1.737237e+01,3.287421e+01,2.744961e+00,8.363621e-01,2.559604e+01,4.272208e+01,3.413513e+01,2.527693e+02,1.948894e+02,2.544150e+02,2.023009e+02
min,0.000000e+00,0.000000e+00,0.000000e+00,NaN,2.000000,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00
25%,2.242000e+03,2.400000e+02,0.000000e+00,NaN,225.000000,8.000000e+00,8.000000e+00,6.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.000000e+00,1.010000e+02,1.700000e+02,2.880000e+02,1.730000e+02,2.700000e+02
50%,4.386000e+03,4.800000e+02,1.000000e+00,NaN,504.000000,2.200000e+01,1.500000e+01,8.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.500000e+00,1.070000e+02,3.990000e+02,4.780000e+02,4.110000e+02,4.780000e+02
75%,6.591000e+03,8.400000e+02,2.400000e+00,NaN,807.000000,3.200000e+01,3.200000e+01,1.350000e+01,2.000000e+00,0.000000e+00,1.000000e+00,1.530000e+01,1.070000e+02,6.180000e+02,6.100000e+02,6.660000e+02,6.100000e+02
max,8.762000e+03,8.634000e+04,3.280000e+03,NaN,1140.000000,7.700000e+01,7.700000e+01,9.002290e+03,4.500000e+02,9.999900e+02,9.993410e+03,9.997160e+03,1.190000e+02,7.840000e+02,7.850000e+02,7.840000e+02,7.850000e+02

In [58]:
# Delete this column due to no values are applicable
del jan['pickup_census_tract']

In [59]:
jan.head(10)

,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,dropoff_census_tract,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_latitude,pickup_longitude,dropoff_latitude,dropoff_longitude
0,85.0,2016-1-13 06:15:00,2016-1-13 06:15:00,180.0,0.40,NaN,24.0,24.0,4.50,0.00,0.0,0.0,4.50,Cash,107.0,199.0,510.0,199.0,510.0
1,2776.0,2016-1-22 09:30:00,2016-1-22 09:45:00,240.0,0.70,NaN,NaN,NaN,4.45,4.45,0.0,0.0,8.90,Credit Card,NaN,NaN,NaN,NaN,NaN
2,3168.0,2016-1-31 21:30:00,2016-1-31 21:30:00,0.0,0.00,NaN,NaN,NaN,42.75,5.00,0.0,0.0,47.75,Credit Card,119.0,NaN,NaN,NaN,NaN
3,4237.0,2016-1-23 17:30:00,2016-1-23 17:30:00,480.0,1.10,NaN,6.0,6.0,7.00,0.00,0.0,0.0,7.00,Cash,NaN,686.0,500.0,686.0,500.0
4,5710.0,2016-1-14 05:45:00,2016-1-14 06:00:00,480.0,2.71,NaN,32.0,NaN,10.25,0.00,0.0,0.0,10.25,Cash,NaN,385.0,478.0,NaN,NaN
5,1987.0,2016-1-8 18:15:00,2016-1-8 18:45:00,1080.0,6.20,NaN,8.0,3.0,17.75,0.00,0.0,0.0,17.75,Cash,NaN,599.0,346.0,660.0,120.0
6,4986.0,2016-1-14 04:30:00,2016-1-14 05:00:00,1500.0,18.40,NaN,NaN,NaN,45.00,12.00,0.0,0.0,57.00,Credit Card,NaN,NaN,NaN,NaN,NaN
7,6400.0,2016-1-26 04:15:00,2016-1-26 04:15:00,60.0,0.20,NaN,16.0,16.0,3.75,0.00,0.0,0.0,3.75,Cash,107.0,527.0,24.0,527.0,24.0
8,7418.0,2016-1-22 11:30:00,2016-1-22 11:45:00,180.0,0.00,504.0,8.0,32.0,5.00,2.00,0.0,1.5,8.50,Credit Card,82.0,210.0,470.0,744.0,605.0
9,6450.0,2016-1-7 21:15:00,2016-1-7 21:15:00,0.0,0.00,NaN,NaN,NaN,3.25,0.00,0.0,1.5,4.75,Cash,NaN,NaN,NaN,NaN,NaN

In [60]:
jan['dropoff_census_tract'].dropna()

8           504.0
10          792.0
11          807.0
13          749.0
15          807.0
16           40.0
19          404.0
20          749.0
21          108.0
23           13.0
25          960.0
26          504.0
30          504.0
31          959.0
34          179.0
36         1077.0
37           16.0
38          504.0
40          805.0
41          805.0
43          792.0
44          787.0
45           16.0
47           13.0
48           16.0
49          787.0
51          134.0
52           16.0
53          911.0
57          515.0
            ...
1705759      40.0
1705760     313.0
1705761      16.0
1705762     615.0
1705763     911.0
1705764     504.0
1705765      16.0
1705766     970.0
1705767     307.0
1705770      40.0
1705771      16.0
1705772     515.0
1705773      16.0
1705775     316.0
1705779     854.0
1705780     504.0
1705784     807.0
1705785     735.0
1705787     970.0
1705789      16.0
1705790     792.0
1705793     178.0
1705794     179.0
1705795    1077.0
1705797     970.0
1705798     504.0
1705799     685.0
1705802     313.0
1705803     807.0
1705804     791.0
Name: dropoff_census_tract, Length: 967479, dtype: float64

In [61]:
jan.dropna()
# jan[pd.notnull(jan.index)]

,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,dropoff_census_tract,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_latitude,pickup_longitude,dropoff_latitude,dropoff_longitude
8,7418.0,2016-1-22 11:30:00,2016-1-22 11:45:00,180.0,0.0,504.0,8.0,32.0,5.00,2.00,0.0,1.5,8.50,Credit Card,82.0,210.0,470.0,744.0,605.0
10,1078.0,2016-1-25 09:00:00,2016-1-25 09:00:00,480.0,1.3,792.0,8.0,8.0,7.00,1.00,0.0,0.0,8.00,Credit Card,109.0,161.0,649.0,419.0,615.0
11,6641.0,2016-1-6 23:15:00,2016-1-6 23:30:00,420.0,0.0,807.0,8.0,28.0,7.25,0.00,0.0,0.0,7.25,Cash,8.0,419.0,615.0,411.0,545.0
13,7984.0,2016-1-22 09:45:00,2016-1-22 09:45:00,420.0,0.0,749.0,8.0,28.0,6.25,0.00,0.0,0.0,6.25,Cash,107.0,419.0,615.0,681.0,196.0
15,221.0,2016-1-3 16:30:00,2016-1-3 16:30:00,720.0,0.0,807.0,7.0,28.0,10.75,0.00,0.0,0.0,10.75,Cash,101.0,642.0,32.0,411.0,545.0
16,6535.0,2016-1-25 10:30:00,2016-1-25 10:30:00,720.0,2.2,40.0,7.0,28.0,10.00,0.00,0.0,0.0,10.00,Cash,92.0,618.0,407.0,395.0,408.0
19,4251.0,2016-1-1 19:30:00,2016-1-1 19:45:00,660.0,4.1,404.0,8.0,6.0,11.85,3.00,0.0,1.0,15.85,Credit Card,101.0,210.0,470.0,606.0,617.0
21,5132.0,2016-1-8 19:30:00,2016-1-8 19:30:00,720.0,0.2,108.0,32.0,24.0,12.25,2.00,0.0,1.0,15.25,Credit Card,8.0,18.0,610.0,472.0,207.0
23,2647.0,2016-1-15 19:30:00,2016-1-15 19:30:00,360.0,0.0,13.0,8.0,8.0,6.50,0.00,0.0,0.0,6.50,Cash,107.0,754.0,410.0,474.0,204.0
26,4126.0,2016-1-23 21:45:00,2016-1-23 21:45:00,360.0,0.0,504.0,8.0,32.0,6.00,0.00,0.0,0.0,6.00,Cash,101.0,688.0,206.0,744.0,605.0
30,373.0,2016-1-2 17:45:00,2016-1-2 17:45:00,240.0,0.6,504.0,8.0,32.0,4.85,0.00,0.0,1.5,6.35,Cash,109.0,688.0,206.0,744.0,605.0
31,5540.0,2016-1-13 19:00:00,2016-1-13 19:15:00,600.0,0.9,959.0,8.0,8.0,7.00,1.11,0.0,0.0,8.11,Credit Card,92.0,754.0,410.0,167.0,754.0
34,4545.0,2016-1-1 00:00:00,2016-1-1 00:00:00,0.0,0.0,179.0,32.0,32.0,0.00,0.00,0.0,0.0,0.00,Cash,119.0,30.0,405.0,30.0,405.0
36,5901.0,2016-1-16 02:45:00,2016-1-16 02:45:00,360.0,0.0,1077.0,8.0,7.0,7.00,2.00,0.0,1.0,10.00,Credit Card,107.0,695.0,366.0,724.0,47.0
40,8102.0,2016-1-18 15:45:00,2016-1-18 16:00:00,480.0,1.6,805.0,32.0,8.0,7.75,0.00,0.0,0.0,7.75,Cash,107.0,64.0,231.0,526.0,511.0
43,7145.0,2016-1-15 13:15:00,2016-1-15 13:15:00,360.0,0.9,792.0,32.0,8.0,6.25,2.00,0.0,0.0,8.25,Credit Card,92.0,744.0,605.0,419.0,615.0
44,7744.0,2016-1-13 16:00:00,2016-1-13 16:00:00,120.0,0.2,787.0,8.0,8.0,4.00,0.00,0.0,1.0,5.00,Cash,107.0,167.0,754.0,161.0,649.0
45,8191.0,2016-1-19 08:30:00,2016-1-19 08:30:00,480.0,0.0,16.0,33.0,32.0,8.50,2.00,0.0,0.0,10.50,Credit Card,8.0,728.0,277.0,18.0,610.0
49,8618.0,2016-1-16 03:00:00,2016-1-16 03:00:00,420.0,0.0,787.0,8.0,8.0,7.00,0.00,0.0,2.0,9.00,Cash,8.0,754.0,410.0,161.0,649.0
51,8247.0,2016-1-2 17:00:00,2016-1-2 17:00:00,360.0,0.9,134.0,8.0,24.0,6.25,0.00,0.0,0.0,6.25,Cash,101.0,754.0,410.0,45.0,163.0
52,8591.0,2016-1-3 03:30:00,2016-1-3 03:45:00,360.0,1.2,16.0,8.0,32.0,6.50,2.00,0.0,1.0,9.50,Credit Card,101.0,695.0,366.0,18.0,610.0
53,4751.0,2016-1-4 11:15:00,2016-1-4 11:15:00,360.0,0.8,911.0,8.0,8.0,5.45,1.00,0.0,0.0,6.45,Credit Card,82.0,167.0,754.0,688.0,206.0
58,7271.0,2016-1-8 10:00:00,2016-1-8 10:15:00,420.0,1.3,504.0,28.0,32.0,6.75,0.00,0.0,1.0,7.75,Cash,3.0,411.0,545.0,744.0,605.0
69,4605.0,2016-1-18 15:15:00,2016-1-18 15:15:00,300.0,0.5,970.0,8.0,8.0,5.25,0.00,0.0,4.0,9.25,Cash,107.0,294.0,113.0,210.0,470.0
72,1748.0,2016-1-21 19:30:00,2016-1-21 19:30:00,360.0,0.0,899.0,32.0,8.0,6.25,0.00,0.0,1.0,7.25,Cash,8.0,18.0,610.0,170.0,351.0
80,2043.0,2016-1-12 10:30:00,2016-1-12 10:45:00,660.0,1.0,307.0,32.0,32.0,7.50,2.00,0.0,1.0,10.50,Credit Card,101.0,18.0,610.0,64.0,231.0
83,6016.0,2016-1-11 23:30:00,2016-1-11 23:30:00,0.0,0.0,313.0,76.0,76.0,3.25,0.00,0.0,0.0,3.25,Cash,8.0,225.0,6.0,225.0,6.0
86,6088.0,2016-1-12 08:15:00,2016-1-12 08:30:00,360.0,0.8,307.0,28.0,32.0,5.75,0.00,0.0,0.0,5.75,Cash,109.0,411.0,545.0,64.0,231.0
92,1603.0,2016-1-8 22:00:00,2016-1-8 22:15:00,900.0,0.3,37.0,8.0,4.0,18.00,3.60,0.0,0.0,21.60,Credit Card,107.0,695.0,366.0,251.0,260.0
93,8169.0,2016-1-19 17:30:00,2016-1-19 18:15:00,2760.0,18.3,16.0,76.0,32.0,46.25,10.05,0.0,4.0,60.30,Credit Card,109.0,225.0,6.0,18.0,610.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1705723,5518.0,2016-1-20 15:45:00,2016-1-20 16:15:00,1620.0,0.6,960.0,32.0,56.0,28.50,7.10,0.0,0.0,35.60,Credit Card,107.0,18.0,610.0,433.0,757.0
1705724,4511.0,2016-1-13 12:45:00,2016-1-13 13:15:00,1440.0,17.8,970.0,76.0,8.0,44.00,9.60,0.0,4.0,57.60,Credit Card,107.0,225.0,6.0,210.0,470.0
1705728,2929.0,2016-1-8 10:45:00,2016-1-8 11:00:00,840.0,0.1,970.0,28.0,8.0,9.75,0.00,0.0,0.0,9.75,Cash,8.0,411.0,545.0,210.0,470.0
1705730,576.0,2016-1-11 17:00:00,2016-1-11 17:15:00,420.0,0.0,787.0,8.0,8.0,6.75,0.00,0.0,0.0,6.75,Cash,107.0,207.0,239.0,161.0,649.0
1705731,6207.0,2016-1-12 09:45:00,2016-1-12 09:45:00,480.0,1.0,504.0,32.0,32.0,6.75,0.00,0.0,0.0,6.75,Cash,109.0,744.0,605.0,744.0,605.0
1705734,3217.0,2016-1-22 19:00:00,2016-1-22 19:00:00,780.0,1.9,1046.0,8.0,33.0,9.50,0.00,0.0,0.0,9.50,Cash,82.0,688.0,206.0,728.0,277.0
1705735,7767.0,2016-1-8 01:00:00,2016-1-8 01:00:00,240.0,0.0,16.0,8.0,32.0,5.50,0.00,0.0,0.0,5.50,Cash,118.0,170.0,351.0,18.0,610.0
1705737,1621.0,2016-1-5 13:00:00,2016-1-5 13:15:00,540.0,0.1,807.0,8.0,28.0,8.50,3.00,0.0,0.0,11.50,Credit Card,107.0,167.0,754.0,411.0,545.0
1705749,1697.0,2016-1-28 17:00:00,2016-1-28 17:00:00,240.0,0.5,504.0,32.0,32.0,5.00,0.00,0.0,0.0,5.00,Cash,109.0,744.0,605.0,744.0,605.0
1705750,6921.0,2016-1-16 20:00:00,2016-1-16 20:00:00,60.0,0.0,364.0,7.0,7.0,3.75,0.00,0.0,1.5,5.25,Cash,107.0,197.0,467.0,151.0,130.0
1705751,4123.0,2016-1-14 15:45:00,2016-1-14 15:45:00,360.0,1.5,807.0,32.0,28.0,6.75,2.00,0.0,0.0,8.75,Credit Card,101.0,30.0,405.0,411.0,545.0
1705754,8169.0,2016-1-20 09:15:00,2016-1-20 09:30:00,360.0,1.5,504.0,8.0,32.0,5.75,2.00,0.0,0.0,7.75,Credit Card,109.0,210.0,470.0,744.0,605.0
1705759,4352.0,2016-1-20 22:30:00,2016-1-20 22:45:00,300.0,0.0,40.0,8.0,28.0,5.75,0.00,0.0,0.0,5.75,Cash,107.0,754.0,410.0,395.0,408.0
1705761,7947.0,2016-1-6 09:00:00,2016-1-6 09:15:00,1380.0,0.3,16.0,6.0,32.0,18.25,3.65,0.0,0.0,21.90,Credit Card,107.0,697.0,693.0,18.0,610.0
1705762,4233.0,2016-1-29 19:15:00,2016-1-29 19:30:00,1020.0,2.1,615.0,6.0,3.0,10.75,0.00,0.0,1.0,11.75,Cash,109.0,697.0,693.0,96.0,716.0
1705763,6108.0,2016-1-16 14:00:00,2016-1-16 14:15:00,300.0,0.9,911.0,8.0,8.0,6.00,0.00,0.0,0.0,6.00,Cash,107.0,419.0,615.0,688.0,206.0
1705765,3265.0,2016-1-5 10:00:00,2016-1-5 10:15:00,600.0,1.5,16.0,33.0,32.0,8.25,0.00,0.0,0.0,8.25,Cash,107.0,728.0,277.0,18.0,610.0
1705766,893.0,2016-1-17 19:00:00,2016-1-17 19:15:00,600.0,3.2,970.0,33.0,8.0,11.50,0.00,0.0,1.0,12.50,Cash,107.0,728.0,277.0,210.0,470.0
1705771,5122.0,2016-1-18 09:45:00,2016-1-18 10:00:00,420.0,0.0,16.0,32.0,32.0,7.25,1.00,0.0,0.0,8.25,Credit Card,107.0,744.0,605.0,18.0,610.0
1705772,715.0,2016-1-1 02:00:00,2016-1-1 02:15:00,960.0,6.0,515.0,24.0,33.0,15.05,0.00,0.0,1.0,16.05,Cash,107.0,472.0,207.0,529.0,619.0
1705773,7744.0,2016-1-13 11:15:00,2016-1-13 11:15:00,240.0,0.6,16.0,8.0,32.0,5.25,2.00,0.0,0.0,7.25,Credit Card,107.0,754.0,410.0,18.0,610.0
1705779,4698.0,2016-1-6 19:45:00,2016-1-6 20:00:00,660.0,2.7,854.0,32.0,33.0,10.75,0.00,0.0,0.0,10.75,Cash,107.0,744.0,605.0,584.0,60.0
1705784,7574.0,2016-1-5 22:00:00,2016-1-5 22:15:00,600.0,3.1,807.0,7.0,28.0,11.25,0.00,0.0,1.0,12.25,Cash,101.0,725.0,518.0,411.0,545.0
1705789,7903.0,2016-1-27 08:45:00,2016-1-27 08:45:00,360.0,0.7,16.0,28.0,32.0,5.50,0.00,0.0,0.0,5.50,Cash,82.0,395.0,408.0,18.0,610.0
1705790,7807.0,2016-1-11 19:00:00,2016-1-11 19:00:00,420.0,0.8,792.0,8.0,8.0,6.00,2.00,0.0,0.0,8.00,Credit Card,107.0,161.0,649.0,419.0,615.0
1705794,5910.0,2016-1-14 11:15:00,2016-1-14 11:15:00,300.0,0.0,179.0,32.0,32.0,5.75,1.50,0.0,0.0,7.25,Credit Card,107.0,18.0,610.0,30.0,405.0
1705795,4579.0,2016-1-29 20:45:00,2016-1-29 20:45:00,360.0,0.0,1077.0,8.0,7.0,6.50,0.00,0.0,1.0,7.50,Cash,8.0,454.0,453.0,724.0,47.0
1705797,918.0,2016-1-9 16:15:00,2016-1-9 16:30:00,900.0,0.1,970.0,33.0,8.0,11.50,2.60,0.0,1.5,15.60,Credit Card,8.0,728.0,277.0,210.0,470.0
1705799,5995.0,2016-1-19 09:00:00,2016-1-19 09:00:00,540.0,0.2,685.0,32.0,7.0,12.25,2.45,0.0,0.0,14.70,Credit Card,8.0,744.0,605.0,408.0,559.0
1705802,1213.0,2016-1-28 06:30:00,2016-1-28 06:45:00,1380.0,17.9,313.0,32.0,76.0,44.00,5.00,0.0,0.0,49.00,Credit Card,92.0,64.0,231.0,225.0,6.0

In [62]:
# jan.describe()
# jan.info()
len(jan.dropna())

615075

In [63]:
feb = pd.read_csv('chicago_taxi_trips_2016_02.csv')
feb.head()

,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_latitude,pickup_longitude,dropoff_latitude,dropoff_longitude
0,53.0,2016-2-28 04:30:00,2016-2-28 04:45:00,840.0,0.30,NaN,NaN,7.0,31.0,15.00,0.0,0.0,0.0,15.00,Cash,8.0,173.0,203.0,558.0,388.0
1,8147.0,2016-2-10 11:30:00,2016-2-10 11:45:00,480.0,1.01,NaN,504.0,28.0,32.0,7.00,1.0,0.0,0.0,8.00,Credit Card,NaN,395.0,408.0,744.0,605.0
2,6234.0,2016-2-18 15:15:00,2016-2-18 15:15:00,180.0,0.40,NaN,16.0,32.0,32.0,4.50,0.0,0.0,0.0,4.50,Cash,NaN,18.0,610.0,18.0,610.0
3,6434.0,2016-2-17 22:00:00,2016-2-17 22:00:00,420.0,2.30,NaN,NaN,NaN,NaN,8.75,0.0,0.0,0.0,8.75,Cash,NaN,NaN,NaN,NaN,NaN
4,64.0,2016-2-22 13:45:00,2016-2-22 14:00:00,1200.0,17.10,NaN,313.0,28.0,76.0,42.00,0.0,0.0,2.0,44.00,Cash,107.0,411.0,545.0,225.0,6.0

In [64]:
del feb['pickup_census_tract']
len(feb.dropna())

646037

In [65]:
# join two dataframes

jan_feb = pd.concat([jan.dropna(), feb.dropna()])
jan_feb.head()

,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,dropoff_census_tract,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_latitude,pickup_longitude,dropoff_latitude,dropoff_longitude
8,7418.0,2016-1-22 11:30:00,2016-1-22 11:45:00,180.0,0.0,504.0,8.0,32.0,5.00,2.0,0.0,1.5,8.50,Credit Card,82.0,210.0,470.0,744.0,605.0
10,1078.0,2016-1-25 09:00:00,2016-1-25 09:00:00,480.0,1.3,792.0,8.0,8.0,7.00,1.0,0.0,0.0,8.00,Credit Card,109.0,161.0,649.0,419.0,615.0
11,6641.0,2016-1-6 23:15:00,2016-1-6 23:30:00,420.0,0.0,807.0,8.0,28.0,7.25,0.0,0.0,0.0,7.25,Cash,8.0,419.0,615.0,411.0,545.0
13,7984.0,2016-1-22 09:45:00,2016-1-22 09:45:00,420.0,0.0,749.0,8.0,28.0,6.25,0.0,0.0,0.0,6.25,Cash,107.0,419.0,615.0,681.0,196.0
15,221.0,2016-1-3 16:30:00,2016-1-3 16:30:00,720.0,0.0,807.0,7.0,28.0,10.75,0.0,0.0,0.0,10.75,Cash,101.0,642.0,32.0,411.0,545.0

In [66]:
len(jan_feb)

1261112